### PR TITLE
Feature/140 python transformation

### PR DESCRIPTION
**Pull request by zzeekk**
### What changes are included in the pull request?
#130 custom transformation in Python
see example in sdl-examples branch https://github.com/smart-data-lake/sdl-examples/tree/feature/130-python-transformation-sandbox

### Why are the changes needed?
Planned feature

### CODE REVIEW

**Comment by zzeekk** [comment]
Hi  @swissrussdev: Is there anyone from your organization who likes to test the Python transformation?

**Comment by pgruetter** [comment]
Couldn't get it running yet, need to downgrade from Python3.8 to 3.7 first.
One thing I noticed already: On some Linux distros (like Ubuntu 20.04) there is no executable called `python` by default, only `python3`. So if you don't create a symlink or install something like `python-is-python3`, you will get an error that it can't find the executable. We should check for that and call `python3` instead in that case.

**Comment by swissrussdev** [comment]
@zzeekk : can't get my hands on someone who ist both python/SDL friendly at the moment

**Comment by raproth** [comment]
Looks fine for me on Windows using the `ab-transform-python` example from sdl-examples, tested with `pythonCode` and `pythonFile` in IntelliJ with Python 3.7.9. I did not really dig into the details of interfacing between python/java, seems quite magical. The only confusing thing is a log during execution:

`2020-09-03 20:24:56 ERROR DAGScheduler:91 - Failed to update accumulator 73 (org.apache.spark.api.python.PythonAccumulatorV2) for task 0
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at org.apache.spark.api.python.PythonAccumulatorV2.openSocket(PythonRDD.scala:640)
	at org.apache.spark.api.python.PythonAccumulatorV2.merge(PythonRDD.scala:664)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$updateAccumulators$1.apply(DAGScheduler.scala:1257)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$updateAccumulators$1.apply(DAGScheduler.scala:1248)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.updateAccumulators(DAGScheduler.scala:1248)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskCompletion(DAGScheduler.scala:1343)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2107)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2059)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2048)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
`

The resulting csv looks fine though. Any idea what that might be?

**Comment by zzeekk** [comment]
> `2020-09-03 20:24:56 ERROR DAGScheduler:91 - Failed to update accumulator 73 (org.apache.spark.api.python.PythonAccumulatorV2) for task 0 java.net.ConnectException: Connection refused: connect at java.net.DualStackPlainSocketImpl.connect0(Native Method) at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) at 

@raproth: i also saw this exception but the result was correct. i think that some there is metric accumulator that is updated from python after the python-jvm connection is already closed. It seems to be some issue in Spark. I would check again in Spark 3.0 if it still exists before digging deeper.

**Comment by raproth** [comment]
I'm not 100% sure, but the docs should be extended in some points:
- install Python plugin in IntelliJ
- Add python to PATH, or extend PATH in the "Run Configuration"

From what I experienced, adding Python/venv to the Project-Structure has no effect during runtime, PYTH and PYTHONPATH are used to locate Python and the libs

**Comment by zzeekk** [comment]
Thanks @raproth, i updated the example readme.

**Comment by zzeekk** [comment]
Hi @pgruetter, i need a reviewer to merge, can you check?

**Review by pgruetter — APPROVED** [review]
Sure, checked it last week but couldn't get it to run under Linux yet. Still think it's good to merge so we have it in 1.1.1.

**Pull request merged**
