### PR TITLE
implement DataObjects with state (#365)

### PR DESCRIPTION
**Pull request by zzeekk**
As preparation for #365 this PR implements execution mode DataObjectStateIncrementalMode and trait CanCreateIncrementalOutput to be implemented by DataObjects.

### CODE REVIEW

**Comment by zzeekk** [comment]
@hiltpold: i renamed method initIncrementalMode to setState as suggested by @pgruetter 

@pgruetter: you were right, setState has to be called in init-phase but also after every increment in postExec.

**Review by hiltpold — APPROVED** [review]

**Review by pgruetter — APPROVED** [review]
LGTM
Only thing I didn't see / test is what happens when you have a DataObject with a state but you don't specify a state file on the command line ?

**Comment by zzeekk** [comment]
> LGTM
> Only thing I didn't see / test is what happens when you have a DataObject with a state but you don't specify a state file on the command line ?

It will be treated as a normal DataObject, no set/getState called.

**Comment by pgruetter** [comment]
> It will be treated as a normal DataObject, no set/getState called.

OK, maybe as an improvement we can find a way to at least warn about that. But it's probably going to be hard.

**Pull request merged**
