### PR TITLE
Update JdbcTableConnection.scala: added properties to pool.

### PR DESCRIPTION
**Pull request by AdiWehrli**
As the `testOnBurrow` property of `BaseGenericObjectPool` is set to `false` as default, we should be able to set this. Additionally I added some more "testOn/While" properties.

Also see issue https://github.com/smart-data-lake/smart-data-lake/issues/794.

### CODE REVIEW

**Comment by AdiWehrli** [comment]
I tested it locally with some log output to check whether the flags were correctly set.

**Comment by AdiWehrli** [comment]
So, now this pull request is ready.

**Comment by zzeekk** [comment]
Great finding! GenericObjectPool supports tests/validations indeed.
We would also need to implement the validation method in JdbcClientPoolFactory, inherited default implementation just returns true:
`override def validateObject(p: PooledObject[SqlConnection]): Boolean`

And question is what query to execute as test. I think we need another configuration property for this query, as it is probably not the same for every database product...

Regarding the new configuration properties - i would suggest to move them into a substructure by creating a `case class ConnectionPoolConfig(maxIdleTimeSec: Int = 3, maxWaitTimeSec: Int = 600, testOnBorrow: Boolean = false, testOnCreate: Boolean = false, testOnReturn: Boolean = false, testWhileIdle: Boolean = false, testQuery: String = <what is a  good default?>)` and a property in JdbcTableConnection `connectionPool: ConnectionPool = ConnectionPool()`
WDYT?

Unfortunately we just merge some changes into develop-spark3 and you need to pull some updates and resolve minor conflicts.

**Comment by AdiWehrli** [comment]
Hello @zzeekk 

Thanks for your answer. That's a good idea to move those properties to a seperate config class. A good default for `testQuery` would be `SELECT 1`, I suppose?

I will pull the changes and resolve the conflicts maybe on Sunday.

Kind regards, 
Adi

**Comment by AdiWehrli** [comment]
Aha, I saw, that the connection properties now are set in `JdbcUtil`. So, I will create a new pull-request, maybe tomorrow.

**Pull request closed without merging**
