### PR TITLE
Feature/102 additional columns

### PR DESCRIPTION
**Pull request by zzeekk**
### What changes are included in the pull request?
#102:
- add additionalColumns attribute to CopyAction, HistorizeAction, DeduplicateAction
- add runtimeOptions attribute to CustomDfTransformer and CustomDfsTransformer
- substitute tokens in transformer.sqlCode with transformer.options/runtimeOptions

### Why are the changes needed?
see #102

### CODE REVIEW

**Review by swissrussdev — COMMENTED** [review]
Looks good - I'm struggling to understand how blacklist/whitelist are now applied: can you help me out?

**Comment by zzeekk** [comment]
Hi @swissrussdev:
Signatur is as follows: "ActionHelper.filterBlacklist(columnBlacklist: Seq[String])(df: DataFrame): DataFrame"
In SparkAction.applyTransformations we only fill the first argument list which results in a partial applied function with Signature "DataFrame => DataFrame". This function we can use in the list of transformers, where we collect all transformations to be applied to the SubFeeds DataFrame. We then apply all transformers by calling multiTransformSubfeed.

Does this answer your question?

**Review by swissrussdev — APPROVED** [review]
Now I see it! OK - nice, very clean. Thanks a lot.

**Comment by zzeekk** [comment]
see also https://github.com/smart-data-lake/sdl-examples/pull/11

**Pull request merged**
