### PR TITLE
Feature/104 fail on configuration objects defined in multiple locations

### PR DESCRIPTION
**Pull request by zzeekk**
see #104: if a configuration objects are defined in multiple locations, a ConfigurationException is thrown.

To be discussed if an exception is the desired behaviour, or if we just want to log a Warning/Error. 
In my opinion we can be strict here, as it's really confusing to define the same configuration object in different locations and have it merged by Hocon.

### CODE REVIEW

**Comment by pgruetter** [comment]
> To be discussed if an exception is the desired behaviour, or if we just want to log a Warning/Error. 
> In my opinion we can be strict here, as it's really confusing to define the same configuration object in different locations and have it merged by Hocon.

I can see complex setups with nested config files in which you define a default object in a parent config and overwrite them in a different config file. 
In these special cases, you would need at least the option to allow overwrites, don't you think?

**Comment by zzeekk** [comment]
> > To be discussed if an exception is the desired behaviour, or if we just want to log a Warning/Error.
> > In my opinion we can be strict here, as it's really confusing to define the same configuration object in different locations and have it merged by Hocon.
> 
> I can see complex setups with nested config files in which you define a default object in a parent config and overwrite them in a different config file.
> In these special cases, you would need at least the option to allow overwrites, don't you think?

Well, the default object already needs to have the correct id. You can't create a default object with a generic id... to create templates we can use hocon inheritance.
But i would not override an action defined in file A in another file... in my opinion it's not a good pattern.
Nevertheless we could create an option to allow duplicates. I think its too much of a detail to add it as command line option, but we could read a system property?

**Review by pgruetter — APPROVED** [review]
Thanks for the addition, I think the environment variable is a good solution.

**Comment by zzeekk** [comment]
Also merged to branch develop

**Pull request merged**
