### PR TITLE
Jdbc connection pool settings

### PR DESCRIPTION
**Pull request by zzeekk**
see #794

### CODE REVIEW

**Comment by AdiWehrli** [comment]
Hello @zzeekk 

It seems ok, but I do not know how to configure ConnectionPoolConfig in SDL. Could you give me a hint, please?

Thanks very much in advance.

Kind regards,
Adi

**Comment by zzeekk** [comment]
Hi @AdiWehrli,

> It seems ok, but I do not know how to configure ConnectionPoolConfig in SDL. Could you give me a hint, please?

With this change ConnectionPoolConfig can be configured as connectionPool property of JdbcTableConnection, e.g. 
```
connections {
  testConnection {
    type = JdbcTableConnection
    url = ...
    driver = ...
    connectionPool {
      testOnBorrow = true
      testOnReturn = true
      ....
    }
  }
}
```

**Comment by AdiWehrli** [comment]
Ah, thanks for the clarification, @zzeekk.

**Review by AdiWehrli — APPROVED** [review]
Ok from my point of view.

**Review by AdiWehrli — APPROVED** [review]

**Review by pgruetter — APPROVED** [review]

**Pull request merged**
