### PR TITLE
Refresh Kafka branch from develop

### PR DESCRIPTION
**Pull request by swissrussdev**
After all the excitement from the "core" changes I would like to test the Kafka connector with the SparkSubFeedsAction, which should now work!

### CODE REVIEW

**Comment by zzeekk** [comment]
Hi @pgruetter , can you check why this pull request triggered action "master release"?

**Comment by pgruetter** [comment]
> Hi @pgruetter , can you check why this pull request triggered action "master release"?

Just saw it, will check thanks

**Comment by kaelte** [comment]
> Hi @swissrussdev , ok for me. Normally we pulled changes from develop directly back to a feature branch without pull request. (Intellij -> VCS -> Git -> Repository -> Pull, then choose branch origin/develop)

I recommend to go one step further:
In case branch develop has received a merge from a feature branch other than the one I am working on, I merge develop into mine.
Like this you will have the merge conflicts earlyier, when merging develop -> feature/myBranch.

**Comment by pgruetter** [comment]
@zzeekk Possibly a UI problem? The build "master release" was only triggered once so far (see actions tab) and that was for the release itself. I'll try to fix the problem first and that we'll check again.

**Comment by swissrussdev** [comment]
> > Hi @swissrussdev , ok for me. Normally we pulled changes from develop directly back to a feature branch without pull request. (Intellij -> VCS -> Git -> Repository -> Pull, then choose branch origin/develop)
> 
> I recommend to go one step further:
> In case branch develop has received a merge from a feature branch other than the one I am working on, I merge develop into mine.
> Like this you will have the merge conflicts earlyier, when merging develop -> feature/myBranch.

Thanks for the heads up - this is what I was trying to do and just wanting to get OK from Zach. Sorry to get everyone involved!

**Pull request merged**
