### PR TITLE
672 - Insert inputIds and outputIds to state file

### PR DESCRIPTION
**Pull request by pgruetter**
Add version number to state file and only accept recovery for state files of same version

### What changes are included in the pull request?
See #672 
Add inputIds and outputIds to state file. 
Also see comment from #671: version number is added in this PR already.

### Why are the changes needed?
Needed by UI to properly show lineage at runtime.

### CODE REVIEW

**Comment by pgruetter** [comment]
@zzeekk Not sure if Environment is the right place to store the hardcoded value for run state format version.

**Comment by zzeekk** [comment]
Hi @pgruetter, great that you do some coding again 👍 
I have some general discussion points:
1. is it a good idea to introduce another version number that we need to manage? Couldn't we reuse SDLB version number? We should put SDLB version and application jar version there in any case for traceability...
2. Shouldn't state file versions be backward compatible, e.g. a newer SDLB version should be able to read/interpret schema files of older versions?

**Comment by pgruetter** [comment]
I thought about these points as well:
1. I would not link it to the SDLB version. The state run format should not change very often (if at all). If we increment the version with each SDLB version (and with that also use SNAPSHOT versions), handling gets more difficult.
2. Generally speaking: yes, they should be. But note that the assertion statement I've inserted is only checked during recoveries. I would argue that you should not have a failed run, then upgrade SDL and try to recover the run. This could lead to all sorts of strange behavior. 
New attributes (like the version number), should be optional so we can read old files though.

Happy to further discuss offline.

**Comment by pgruetter** [comment]
@zzeekk As discussed: RunStateFormatVersion changed to Int and moved from Environment to Object. Will insert SDLB version info in a separate PR.

**Review by zzeekk — APPROVED** [review]
LGTM

**Pull request merged**
